export const FETCH_FILM = 'FETCH_FILM';
export const FETCH_FILM_DANG_CHIEU = 'FETCH_FILM_DANG_CHIEU';
export const FETCH_FILM_SAP_CHIEU = 'FETCH_FILM_SAP_CHIEU';
export const FETCH_ALL_FILM = 'FETCH_ALL_FILM';
