export const FETCH_CHI_TIET_PHONG_VE = 'FETCH_CHI_TIET_PHONG_VE';
export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT';
export const CHUYEN_TAB = ' CHUYEN_TAB';
export const DAT_GHE = 'DAT_GHE';
export const SET_DANH_SACH_GHE_KHACH_DAT = 'SET_DANH_SACH_GHE_KHACH_DAT';
